/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and kept here so Phase 0 typecheck can run
// before the dev server has generated it.
