type EnvKey =
  | "AUTH_SECRET"
  | "COURSEBUILDER_APP_URL"
  | "COURSEBUILDER_URL"
  | "DATABASE_URL"
  | "EGGHEAD_BETA_DB_APPROVED"
  | "EGGHEAD_RUNTIME"
  | "EGGHEAD_SUBSCRIPTION_PRODUCT_ID"
  | "GITHUB_CLIENT_ID"
  | "GITHUB_CLIENT_SECRET"
  | "INNGEST_EVENT_KEY"
  | "INNGEST_SIGNING_KEY"
  | "NEXT_PUBLIC_APP_URL"
  | "POSTMARK_API_KEY"
  | "POSTMARK_FROM_EMAIL"
  | "STRIPE_SECRET_TOKEN"
  | "STRIPE_WEBHOOK_SECRET"
  | "URL";

export function getEnv(name: EnvKey) {
  return process.env[name];
}
