import { courseBuilderAdapter, db } from '@/db'
import { merchantPrice, merchantProduct } from '@/db/schema'
import { env } from '@/env.mjs'
import type { EggheadSale, Event } from '@/lib/events'
import { and, eq } from 'drizzle-orm'
import Stripe from 'stripe'

import { formatMonthDay } from './live-workshop'

/**
 * Stripe objects the live egghead.io site needs on top of what the Builder
 * already creates (Stripe product + price): a Payment Link and three promo
 * codes. Everything here is scoped to the event's own Stripe product.
 */

let client: Stripe | null = null

export function getStripe() {
	if (!client) {
		client = new Stripe(env.STRIPE_SECRET_TOKEN)
	}
	return client
}

export type EventCommerce = {
	productId: string
	stripeProductId: string
	stripePriceId: string
	/** dollars */
	price: number
	/** -1 means unlimited */
	quantityAvailable: number
}

/**
 * Resolve the Course Builder product and its Stripe counterparts for an event.
 * Throws a clear error when the event was created without a price.
 */
export async function resolveCommerceForEvent(
	event: Event,
): Promise<EventCommerce> {
	const productId = event.resourceProducts?.[0]?.productId
	if (!productId) {
		throw new Error(
			`Event ${event.fields.slug} has no product. Create it with a price so the Builder makes the Stripe product and price.`,
		)
	}

	const [product, price] = await Promise.all([
		courseBuilderAdapter.getProduct(productId),
		courseBuilderAdapter.getPriceForProduct(productId),
	])

	if (!product) {
		throw new Error(`Product ${productId} for ${event.fields.slug} was not found.`)
	}
	if (!price) {
		throw new Error(`Product ${productId} for ${event.fields.slug} has no price.`)
	}

	// The published adapter's getMerchantPriceForProductId filters merchantPrice
	// by merchantProductId = productId, which never matches. Read the rows directly.
	const merchantProductRow = await db.query.merchantProduct.findFirst({
		where: and(eq(merchantProduct.productId, productId), eq(merchantProduct.status, 1)),
	})
	const merchantPriceRow = merchantProductRow
		? await db.query.merchantPrice.findFirst({
				where: and(
					eq(merchantPrice.merchantProductId, merchantProductRow.id),
					eq(merchantPrice.status, 1),
				),
			})
		: null

	if (!merchantProductRow?.identifier || !merchantPriceRow?.identifier) {
		throw new Error(
			`Product ${productId} for ${event.fields.slug} has no Stripe product or price. The adapter may have failed silently at creation.`,
		)
	}

	return {
		productId,
		stripeProductId: merchantProductRow.identifier,
		stripePriceId: merchantPriceRow.identifier,
		price: Number(price.unitAmount),
		quantityAvailable: product.quantityAvailable ?? -1,
	}
}

export type ExistingPromoCode = {
	code: string
	amountOff: number | null
	percentOff: number | null
	couponName: string | null
	active: boolean
}

/**
 * The promo codes already in Stripe, most recent first. The dry run shows
 * these so the proposed codes visibly follow the existing pattern.
 */
/**
 * The runtime SDK (stripe@22, API 2026-08-26) nests the coupon under
 * `promotion`, while the type definitions the app compiles against still
 * come from the older stripe@16 that @coursebuilder/core depends on and
 * put it at `coupon`. Read whichever is present; it is an object only when
 * expanded.
 */
type PromotionCodeLike = {
	promotion?: { coupon?: string | Stripe.Coupon | null } | null
	coupon?: string | Stripe.Coupon | null
}

function couponOf(code: PromotionCodeLike): Stripe.Coupon | null {
	const coupon = code.promotion?.coupon ?? code.coupon
	return coupon && typeof coupon === 'object' ? coupon : null
}

export async function listExistingPromoCodes(
	limit = 30,
): Promise<ExistingPromoCode[]> {
	const stripe = getStripe()
	const codes = await stripe.promotionCodes.list({
		limit,
		expand: ['data.promotion.coupon'],
	})
	return codes.data.map((code) => {
		const coupon = couponOf(code)
		return {
			code: code.code,
			amountOff: coupon?.amount_off != null ? coupon.amount_off / 100 : null,
			percentOff: coupon?.percent_off ?? null,
			couponName: coupon?.name ?? null,
			active: code.active,
		}
	})
}

/**
 * Coupon names follow the existing Stripe pattern, e.g.
 * `asfw-08-07-yearly-member-discount`, `asfw-08-07-non-member-early-bird`,
 * `asfw-08-07-member-early-bird`. Promo codes are generated by Stripe unless
 * given explicitly, matching the random codes on previous workshops.
 */
export function couponNames(prefix: string, monthDay: string) {
	return {
		member: `${prefix}-${monthDay}-yearly-member-discount`,
		earlyBird: `${prefix}-${monthDay}-non-member-early-bird`,
		earlyBirdMember: `${prefix}-${monthDay}-member-early-bird`,
	}
}

/** Unix seconds for 23:59:59 of `yyyy-mm-dd` in `timeZone`. */
export function endOfDayInTimeZone(dateStr: string, timeZone: string) {
	const naive = new Date(`${dateStr}T23:59:59Z`)
	const parts = new Intl.DateTimeFormat('en-US', {
		timeZone,
		timeZoneName: 'longOffset',
	}).formatToParts(naive)
	const raw = parts.find((part) => part.type === 'timeZoneName')?.value ?? 'GMT'
	const match = raw.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/)
	const sign = match?.[1] === '-' ? -1 : 1
	const hours = match ? Number(match[2]) : 0
	const minutes = match?.[3] ? Number(match[3]) : 0
	const offsetSeconds = sign * (hours * 3600 + minutes * 60)
	return Math.floor(naive.getTime() / 1000) - offsetSeconds
}

export type SaleOptions = {
	flagKey: string
	/** Coupon name prefix matching previous workshops, e.g. "asfw" or "CC". */
	couponNamePrefix: string
	/** Existing workshops never expire early-bird codes; the page stops offering them. Default false. */
	expireEarlyBirdCodes?: boolean
	/** Explicit promo codes. Leave unset to let Stripe generate them. */
	memberCode?: string
	earlyBirdCode?: string
	earlyBirdMemberCode?: string
	memberDiscount: number
	earlyBirdDiscount: number
	earlyBirdMemberDiscount: number
	earlyBirdEndDate?: string | null
	isEuFriendly?: boolean
	bannerMessage?: string | null
	earlyBirdBannerMessage?: string | null
	afterCompletionUrl?: string | null
}

export type PromoCodePlan = {
	/** Stripe coupon name */
	name: string
	/** null = Stripe generates the code */
	code: string | null
	amountOff: number
	expiresAt: number | null
	reuseId: string | null
}

export type SalePlan = {
	eventId: string
	slug: string
	commerce: EventCommerce
	options: SaleOptions
	paymentLink: { reuseId: string | null; reuseUrl: string | null }
	promoCodes: {
		member: PromoCodePlan
		earlyBird: PromoCodePlan
		earlyBirdMember: PromoCodePlan
	}
	existingCodes: ExistingPromoCode[]
}

/**
 * Work out exactly what `executeSale` would create, without creating it.
 * Reuses the Payment Link and any promo code already recorded on the event.
 */
export async function planSale(event: Event, options: SaleOptions): Promise<SalePlan> {
	const commerce = await resolveCommerceForEvent(event)
	const existing = await listExistingPromoCodes()
	const timeZone = event.fields.timezone || 'America/Los_Angeles'
	if (!event.fields.startsAt) {
		throw new Error(`Event ${event.fields.slug} needs a start date before creating its sale.`)
	}
	const names = couponNames(
		options.couponNamePrefix,
		formatMonthDay(new Date(event.fields.startsAt), timeZone),
	)
	const earlyBirdExpires =
		options.expireEarlyBirdCodes && options.earlyBirdEndDate
			? endOfDayInTimeZone(options.earlyBirdEndDate, timeZone)
			: null
	const current = event.fields.eggheadSale

	return {
		eventId: event.id,
		slug: event.fields.slug,
		commerce,
		options,
		paymentLink: {
			reuseId: current?.paymentLinkId ?? null,
			reuseUrl: current?.paymentLinkUrl ?? null,
		},
		promoCodes: {
			member: {
				name: names.member,
				code: current?.promoCodes.member.code ?? options.memberCode ?? null,
				amountOff: options.memberDiscount,
				expiresAt: null,
				reuseId: current?.promoCodes.member.id ?? null,
			},
			earlyBird: {
				name: names.earlyBird,
				code: current?.promoCodes.earlyBird.code ?? options.earlyBirdCode ?? null,
				amountOff: options.earlyBirdDiscount,
				expiresAt: earlyBirdExpires,
				reuseId: current?.promoCodes.earlyBird.id ?? null,
			},
			earlyBirdMember: {
				name: names.earlyBirdMember,
				code:
					current?.promoCodes.earlyBirdMember.code ?? options.earlyBirdMemberCode ?? null,
				amountOff: options.earlyBirdMemberDiscount,
				expiresAt: earlyBirdExpires,
				reuseId: current?.promoCodes.earlyBirdMember.id ?? null,
			},
		},
		existingCodes: existing.slice(0, 12),
	}
}

async function createPromoCode(
	stripe: Stripe,
	plan: PromoCodePlan,
	stripeProductId: string,
): Promise<EggheadSale['promoCodes']['member']> {
	if (plan.reuseId) {
		const existing = await stripe.promotionCodes.retrieve(plan.reuseId, {
			expand: ['promotion.coupon'],
		})
		const coupon = couponOf(existing)
		return {
			id: existing.id,
			code: existing.code,
			couponId: coupon?.id ?? '',
			amountOff: (coupon?.amount_off ?? 0) / 100,
			expiresAt: existing.expires_at
				? new Date(existing.expires_at * 1000).toISOString()
				: null,
		}
	}

	const coupon = await stripe.coupons.create({
		name: plan.name,
		amount_off: Math.round(plan.amountOff * 100),
		currency: 'usd',
		duration: 'once',
		applies_to: { products: [stripeProductId] },
	})
	// See PromotionCodeLike: the 2026 API wants `promotion`, the compiled-against
	// types still expect `coupon`. The API rejects unknown params, so send the new shape.
	const createParams = {
		promotion: { type: 'coupon', coupon: coupon.id },
		...(plan.code ? { code: plan.code } : {}),
		...(plan.expiresAt ? { expires_at: plan.expiresAt } : {}),
	}
	const promotionCode = await stripe.promotionCodes.create(
		createParams as unknown as Stripe.PromotionCodeCreateParams,
	)
	return {
		id: promotionCode.id,
		code: promotionCode.code,
		couponId: coupon.id,
		amountOff: plan.amountOff,
		expiresAt: plan.expiresAt ? new Date(plan.expiresAt * 1000).toISOString() : null,
	}
}

/**
 * Create the Payment Link and promo codes described by `plan`.
 * Returns the `eggheadSale` record to store on the event.
 */
export async function executeSale(plan: SalePlan): Promise<EggheadSale> {
	const stripe = getStripe()
	const { stripeProductId, stripePriceId } = plan.commerce

	let paymentLinkId = plan.paymentLink.reuseId
	let paymentLinkUrl = plan.paymentLink.reuseUrl
	if (!paymentLinkId || !paymentLinkUrl) {
		const metadata = { productId: stripeProductId, eventId: plan.eventId }
		const link = await stripe.paymentLinks.create({
			line_items: [{ price: stripePriceId, quantity: 1 }],
			allow_promotion_codes: true,
			metadata,
			payment_intent_data: { metadata },
			...(plan.options.afterCompletionUrl
				? {
						after_completion: {
							type: 'redirect',
							redirect: { url: plan.options.afterCompletionUrl },
						},
					}
				: {}),
		})
		paymentLinkId = link.id
		paymentLinkUrl = link.url
	}

	const member = await createPromoCode(stripe, plan.promoCodes.member, stripeProductId)
	const earlyBird = await createPromoCode(stripe, plan.promoCodes.earlyBird, stripeProductId)
	const earlyBirdMember = await createPromoCode(
		stripe,
		plan.promoCodes.earlyBirdMember,
		stripeProductId,
	)

	return {
		flagKey: plan.options.flagKey,
		stripeProductId,
		stripePriceId,
		paymentLinkId,
		paymentLinkUrl,
		promoCodes: { member, earlyBird, earlyBirdMember },
		earlyBirdEndDate: plan.options.earlyBirdEndDate ?? null,
		isEuFriendly: plan.options.isEuFriendly ?? false,
		bannerMessage: plan.options.bannerMessage ?? null,
		earlyBirdBannerMessage: plan.options.earlyBirdBannerMessage ?? null,
		approvedBy: null,
		approvedAt: null,
	}
}

export type StripeSaleState = {
	paymentLink: { id: string; url: string; active: boolean } | null
	promoCodes: Array<{
		role: 'member' | 'earlyBird' | 'earlyBirdMember'
		id: string
		code: string
		active: boolean
		amountOff: number | null
		expiresAt: string | null
	}>
	product: { id: string; name: string; active: boolean } | null
	price: { id: string; unitAmount: number | null; active: boolean } | null
}

/** Read the live Stripe state for a recorded sale, for the review page and drift check. */
export async function readStripeSaleState(sale: EggheadSale): Promise<StripeSaleState> {
	const stripe = getStripe()
	const [link, product, price, ...codes] = await Promise.all([
		stripe.paymentLinks.retrieve(sale.paymentLinkId).catch(() => null),
		stripe.products.retrieve(sale.stripeProductId).catch(() => null),
		stripe.prices.retrieve(sale.stripePriceId).catch(() => null),
		...(['member', 'earlyBird', 'earlyBirdMember'] as const).map((role) =>
			stripe.promotionCodes
				.retrieve(sale.promoCodes[role].id, { expand: ['promotion.coupon'] })
				.then((code) => ({ role, code }))
				.catch(() => ({ role, code: null })),
		),
	])
	return {
		paymentLink: link ? { id: link.id, url: link.url, active: link.active } : null,
		product: product ? { id: product.id, name: product.name, active: product.active } : null,
		price: price
			? {
					id: price.id,
					unitAmount: price.unit_amount != null ? price.unit_amount / 100 : null,
					active: price.active,
				}
			: null,
		promoCodes: codes.flatMap(({ role, code }) =>
			code
				? [
						{
							role,
							id: code.id,
							code: code.code,
							active: code.active,
							amountOff:
								couponOf(code)?.amount_off != null ? (couponOf(code)?.amount_off ?? 0) / 100 : null,
							expiresAt: code.expires_at
								? new Date(code.expires_at * 1000).toISOString()
								: null,
						},
					]
				: [],
		),
	}
}
