import { getCourseBuilderSchema } from "@coursebuilder/adapter-drizzle/mysql";

import { mysqlTable } from "./mysql-table";
import { getEggheadUsersSchema } from "./users";

export const eggheadCourseBuilderSchema = getCourseBuilderSchema(mysqlTable, {
  getUsersSchema: getEggheadUsersSchema,
});

export const {
  accounts,
  accountsRelations,
  profiles,
  profilesRelations,
  permissions,
  permissionsRelations,
  rolePermissions,
  rolePermissionsRelations,
  roles,
  rolesRelations,
  sessions,
  sessionsRelations,
  userPermissions,
  userPermissionsRelations,
  userRoles,
  userRolesRelations,
  verificationTokens,
  communicationChannel,
  communicationPreferenceTypes,
  communicationPreferences,
  communicationPreferencesRelations,
  contentContributions,
  contentContributionRelations,
  contentResource,
  contentResourceRelations,
  contentResourceVersion,
  contentResourceVersionRelations,
  contentResourceResource,
  contentResourceResourceRelations,
  contributionTypes,
  contributionTypesRelations,
  resourceProgress,
  contentResourceTag,
  contentResourceTagRelations,
  tag,
  tagRelations,
  tagTag,
  tagTagRelations,
  deviceVerifications,
  deviceVerificationRelations,
  deviceAccessToken,
  deviceAccessTokenRelations,
  organization,
  organizationRelations,
  organizationMemberships,
  organizationMembershipRelations,
  organizationMembershipRoles,
  organizationMembershipRolesRelations,
  coupon,
  couponRelations,
  merchantAccount,
  merchantCharge,
  merchantChargeRelations,
  merchantCoupon,
  merchantCustomer,
  merchantPrice,
  merchantProduct,
  merchantSession,
  prices,
  products,
  productRelations,
  purchases,
  purchaseRelations,
  purchaseUserTransfer,
  purchaseUserTransferRelations,
  contentResourceProduct,
  contentResourceProductRelations,
  entitlements,
  entitlementsRelations,
  entitlementTypes,
} = eggheadCourseBuilderSchema;

export const users = eggheadCourseBuilderSchema.users;
export const usersRelations = eggheadCourseBuilderSchema.usersRelations;
